#
#Fri Mar 13 09:59:28 PET 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*, --start-maximized, \\n--test-type, \\n--no-sandbox, \\n--ignore-certificate-errors, \\n--window-size\=1920,1080, \\n--disable-save-password-bubble, \\n--disable-notifications, \\n--disable-infobars, \\n--disable-extensions], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
